# Generated by Django 4.2.11 on 2024-04-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_alter_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
    ]
