# Generated by Django 4.2.11 on 2024-04-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0012_remove_product_brand_remove_product_category_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
