# Generated by Django 4.2.11 on 2024-05-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0017_alter_customer_address_alter_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
