# Generated by Django 4.2.11 on 2024-05-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0018_customer_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ref',
        ),
    ]
