# Generated by Django 4.2.11 on 2024-04-20 13:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='participant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='main_stack',
            field=models.CharField(choices=[('backend engineer', 'backend engineer'), ('software developer', 'software developer'), ('web developer', 'web developer'), ('system administration', 'system administrator'), ('mobile developer', 'mobile developer'), ('IT Support', 'IT Support'), ('Teacher', 'Teacher'), ('Administrator', 'Administrator'), ('coder', 'coder'), ('engineer', 'engineer')], default=('backend engineer', 'backend engineer'), max_length=50),
        ),
    ]
