# Generated by Django 4.2.11 on 2024-04-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_room_participant_alter_user_main_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auths.topic'),
        ),
    ]
