# Generated by Django 4.2.11 on 2024-04-24 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0009_message_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='status',
        ),
    ]
