# Generated by Django 4.2.11 on 2024-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0014_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='hobbies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icons',
            field=models.ImageField(blank=True, default='../static/images/gallery/cd-icon-navigation.svg', null=True, upload_to='icons'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='stack',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
