# Generated by Django 4.2.11 on 2024-05-12 12:38

import auths.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0015_alter_skill_hobbies_alter_skill_icons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('apartment', models.CharField(blank=True, max_length=150, null=True)),
                ('town', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(default=0, max_length=6, validators=[auths.models.is_digit])),
                ('order_note', models.CharField(blank=True, max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
