# Generated by Django 4.2.11 on 2024-05-06 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_brand_options_alter_subcat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcat',
            options={'ordering': ['-date_created', '-date_updated'], 'verbose_name': 'Sub-Category'},
        ),
        migrations.RemoveField(
            model_name='brand',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon_image',
        ),
        migrations.RemoveField(
            model_name='subcat',
            name='description',
        ),
    ]
