# Generated by Django 4.2.11 on 2024-05-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_attachments_product_image_remove_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='../static/img/testimonial-1.jpg', upload_to='images/'),
        ),
    ]
