# Generated by Django 4.2.11 on 2024-05-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_category_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='top_rated',
            field=models.BooleanField(default=False),
        ),
    ]
