# Generated by Django 4.2.11 on 2024-05-12 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_brand_name_alter_subcat_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-date_created', '-date_updated']},
        ),
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ['-date_created', '-date_updated']},
        ),
    ]
