# Generated by Django 4.2.11 on 2024-05-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_category_icons_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attachments',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
