# Generated by Django 4.2.11 on 2024-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_cartproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
