# Generated by Django 4.2.11 on 2024-05-13 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.cartproduct'),
        ),
    ]
