# Generated by Django 4.2.11 on 2024-05-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_recentview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
