# Generated by Django 4.2.11 on 2024-05-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date_created', '-date_updated'], 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AddField(
            model_name='purchase',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
