# Generated by Django 4.2.11 on 2024-05-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_remove_purchase_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='verified',
        ),
        migrations.AddField(
            model_name='cart',
            name='ref',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
