# Generated by Django 4.2.11 on 2024-05-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_remove_purchase_verified_cart_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.PositiveBigIntegerField(default=1000),
        ),
    ]
